name: gifdi
networks:
  gifdi:
    name: gifdi
services:
  gifdi-postgres:
    image: postgres
    hostname: postgres
    container_name: gifdi-postgres
    ports: ['${POSTGRES_PORT:?}:5432']
    volumes: ['gifdi-postgres:/var/lib/postgresql/data']
    networks: ['gifdi']
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      start_period: 10s
volumes:
  gifdi-postgres: